---
development:
  cloud_name: dojeutmz9
  api_key: '783688466829137'
  api_secret: aKS2YgrJ4ydoWvkkBwWtxPEVh2M
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dojeutmz9
  api_key: '783688466829137'
  api_secret: aKS2YgrJ4ydoWvkkBwWtxPEVh2M
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dojeutmz9
  api_key: '783688466829137'
  api_secret: aKS2YgrJ4ydoWvkkBwWtxPEVh2M
  enhance_image_tag: true
  static_image_support: false
